global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: [ 'app:5000' ]

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'promtail'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'promtail:9080' ]

  - job_name: 'grafana'
    static_configs:
      - targets:
          - 'grafana:3000'